#!/usr/bin/perl
$stdin = 0;
if ($ARGV[0] eq "-") {
	$stdin = 1;
	open dest, ">", $ARGV[1];
} elsif ($ARGV[1] eq "-" ) {
	$stdin = 1;
	open dest, ">", $ARGV[0];
} else {
	open source, "<", $ARGV[0];
	open dest, ">", $ARGV[1];
}
if($stdin == 0) {
	rename $ARGV[0], $ARGV[1];
	#	while(<source>) {
	#		print dest;
	#}
} else {
	while(<STDIN>) {
		print dest;
	}
}